FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu

RUN apt update && apt install -y nfs-common

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV NFSMOUNT "/nfsroot"
ENV NFS_HOST "127.0.0.1"
RUN mkdir ${NFSMOUNT}
ENTRYPOINT ["/entrypoint.sh"]
