FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu

RUN apt update && apt install -y nfs-common nfs-kernel-server

ENV NFSMOUNT "/nfsroot"
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN mkdir "${NFSMOUNT}"
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
